### ISSUE TITLE
screeenshots

### ISSUE THREAD

**Issue by CLIFF-MUDIGO** [CLIFF-MUDIGO/ejs-challenge#1]
![Screenshot from 2023-11-23 23-32-51](https://github.com/CLIFF-MUDIGO/ejs-challenge/assets/59367121/9c76db95-b262-4eec-a220-08b4b6b3809f)
![Screenshot from 2023-11-23 23-31-35](https://github.com/CLIFF-MUDIGO/ejs-challenge/assets/59367121/bed95fec-3df6-47b6-9516-f3750f579c22)
![Screenshot from 2023-11-23 23-31-07](https://github.com/CLIFF-MUDIGO/ejs-challenge/assets/59367121/1b883421-56cd-491d-816e-81ad785b5e62)
![Screenshot from 2023-11-23 23-30-52](https://github.com/CLIFF-MUDIGO/ejs-challenge/assets/59367121/b5160b6e-20ea-49b0-b3c7-1014444b7761)

**Comment by belam123** [comment]
Add more screenshots
